version: '3.4'

services:
  billmanager.api:
    image: ${DOCKER_REGISTRY-}billmanagerapi
    build:
      context: .
      dockerfile: BillManager.Api/Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - "db"
    environment:
      - ConnectionStrings__BillManagerDbContext=Server=db;Database=BillManagerContext;User ID=SA;Password=TestPassword1;MultipleActiveResultSets=true
      - ASPNETCORE_ENVIRONMENT=Production
      - UpgradeDatabase=True
    restart: always


  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "TestPassword1"
      ACCEPT_EULA: "Y"
